name: react-query tests

on:
  push:

jobs:
  test:
    name: 'Node ${{ matrix.node }}, React ${{ matrix.react }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
        react: [17, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - run: yarn test:ci
        env:
          REACTJS_VERSION: ${{ matrix.react }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
